# Generated by Django 2.1.2 on 2021-11-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_item_sample_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sample_1_1_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='淡水取水ポンプ1\u3000電流（A)'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_1_1_2',
            field=models.FloatField(blank=True, null=True, verbose_name='淡水取水ポンプ1\u3000稼働時間（hr)'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_1_1_3',
            field=models.IntegerField(blank=True, choices=[(1, '正常'), (2, '異常')], null=True, verbose_name='淡水取水ポンプ1\u3000異常の有無'),
        ),
    ]
