# Generated by Django 2.1.2 on 2021-11-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211119_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sample_1_2_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='「淡水ポンプ室」淡水取水ポンプ2\u3000電流（A)'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_1_2_2',
            field=models.FloatField(blank=True, null=True, verbose_name='「淡水ポンプ室」淡水取水ポンプ2\u3000稼働時間（hr)'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_1_2_3',
            field=models.IntegerField(blank=True, choices=[(1, '正常'), (2, '異常')], null=True, verbose_name='「淡水ポンプ室」淡水取水ポンプ2\u3000異常の有無'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_2_1_1',
            field=models.FloatField(blank=True, null=True, verbose_name='「調餌室」冷蔵庫\u3000庫内温度（℃)'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_2_1_2',
            field=models.IntegerField(blank=True, choices=[(1, '正常'), (2, '異常')], null=True, verbose_name='「調餌室」冷凍庫\u3000異常の有無'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_2_2_1',
            field=models.FloatField(blank=True, null=True, verbose_name='「調餌室」冷凍庫\u3000庫内温度（℃)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_1_1_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='「淡水ポンプ室」淡水取水ポンプ1\u3000電流（A)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_1_1_2',
            field=models.FloatField(blank=True, null=True, verbose_name='「淡水ポンプ室」淡水取水ポンプ1\u3000稼働時間（hr)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_1_1_3',
            field=models.IntegerField(blank=True, choices=[(1, '正常'), (2, '異常')], null=True, verbose_name='「淡水ポンプ室」淡水取水ポンプ1\u3000異常の有無'),
        ),
    ]
