# Generated by Django 2.1.2 on 2021-11-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211119_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sample_2_2_2',
            field=models.IntegerField(blank=True, choices=[(1, '正常'), (2, '異常')], null=True, verbose_name='「調餌室」冷凍庫\u3000異常の有無'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_3_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='「研究室」海水受水槽\u3000水位（cm)'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_3_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='「研究室」淡水受水槽\u3000水位（cm)'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_4_1_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='「機械室 2F」 海水揚水ポンプ1\u3000電流（A)'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_4_1_2',
            field=models.FloatField(blank=True, null=True, verbose_name='「機械室 2F」 海水揚水ポンプ1\u3000稼働時間（hr)'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_4_1_3',
            field=models.IntegerField(blank=True, choices=[(1, '正常'), (2, '異常')], null=True, verbose_name='「機械室 2F」 海水揚水ポンプ1\u3000異常の有無'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_4_2_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='「機械室 2F」 海水揚水ポンプ2\u3000電流（A)'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_4_2_2',
            field=models.FloatField(blank=True, null=True, verbose_name='「機械室 2F」 海水揚水ポンプ2\u3000稼働時間（hr)'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_4_2_3',
            field=models.IntegerField(blank=True, choices=[(1, '正常'), (2, '異常')], null=True, verbose_name='「機械室 2F」 海水揚水ポンプ2\u3000異常の有無'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_4_3_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='「機械室 2F」 海水揚水ポンプ3\u3000電流（A)'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_4_3_2',
            field=models.FloatField(blank=True, null=True, verbose_name='「機械室 2F」 海水揚水ポンプ3\u3000稼働時間（hr)'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_4_3_3',
            field=models.IntegerField(blank=True, choices=[(1, '正常'), (2, '異常')], null=True, verbose_name='「機械室 2F」 海水揚水ポンプ3\u3000異常の有無'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_2_1_2',
            field=models.IntegerField(blank=True, choices=[(1, '正常'), (2, '異常')], null=True, verbose_name='「調餌室」冷蔵庫\u3000異常の有無'),
        ),
    ]
