# Generated by Django 2.1.2 on 2021-11-19 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211119_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sample_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_10', to=settings.AUTH_USER_MODEL, verbose_name='点検者'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_7',
            field=models.DateField(blank=True, null=True, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_8',
            field=models.DateTimeField(blank=True, null=True, verbose_name='日時'),
        ),
    ]
