# Generated by Django 2.1.2 on 2021-11-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211119_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sample_8',
            field=models.TimeField(blank=True, null=True, verbose_name='点検時間'),
        ),
    ]
